# ~/.config/yazi/yazi.toml

[opener]
# A única regra necessária aqui é a de arquivos .url,
# pois ela usa um script customizado para extrair o link.
# As outras associações agora são gerenciadas pelo sistema.
url = [
    { run = "firefox \"$(grep -oP '^URL=\\K.*' '$@')\"", block = false, desc = "Abrir URL no Firefox" },
]

# A partir daqui, você pode adicionar outras configurações do Yazi
# que não sejam relacionadas a abridores de arquivo (openers).
